name: oauth_do
description: Device flow OAuth SDK for the .do platform.
version: 0.1.0
homepage: https://github.com/drivly/oauth.do
repository: https://github.com/drivly/oauth.do

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
